MLOpsTool/Data/urls.py
from django.conf.urls import url
from . import views

app_name = "Data"

urlpatterns = [
    url(r'data/list/', views.DataListView.as_view(), name="data_list"),
    url(r'data/detail/(?P<pk>\w+)/', views.DataDetailView.as_view(),
        name="data_detail"),
    url(r'data/create/', views.DataCreateView.as_view(), name="data_create"),
]

MLOpsTool/MLOpsTool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("User.urls", namespace='User')),
    path('', include("Tag.urls", namespace='Tag')),
    path('', include("Data.urls", namespace='Data')),
    path('', include("Pipeline.urls", namespace='Pipeline')),
    path('', include("Model.urls", namespace='Model')),
    path('', include("PreProcessing.urls", namespace='PreProcessing')),
    path('', include("Project.urls", namespace='Project'))
]

MLOpsTool/Project/urls.py
from django.conf.urls import url
from Project import views


app_name = "Project"

urlpatterns = [
    url(r'project/list/', views.ProjectListView.as_view(),
        name='list_project'),
    url(r'project/create/', views.ProjectCreateView.as_view(),
        name='create_project'),
    url(r'project/detail/(?P<pk>\w+)/', views.ProjectDetailView.as_view(),
        name='detail_project'),

]

MLOpsTool/Tag/urls.py
from django.conf.urls import url
from . import views

app_name = "Tag"

urlpatterns = [
    url(r'tag/list/', views.TagListView.as_view(), name="tag_list"),
    url(r'tag/detail/(?P<pk>\d+)/', views.TagDetailView.as_view(),
        name="tag_detail"),
    url(r'tag/create/', views.TagCreateView.as_view(), name="tag_create"),
]

MLOpsTool/User/urls.py
from django.conf.urls import url
from django.urls import path
from User.views import (
    CreateUser,
    LoginView,
    user_logout,
)

app_name = "User"
urlpatterns = [
    path('', LoginView.as_view(), name='login_view'),
    url(r'user/create/', CreateUser.as_view(), name='create_user'),
    url(r'user/logout/', user_logout, name='user_logout')
]

MLOpsTool/templates/includes/add_button_view.html
<div>
  <a href="{{urls}}" class="btn btn-secondary mt-3 mb-3" role="button">+</a>
</div>

MLOpsTool/templates/includes/list_object_view.html
<div class="conteiner-fluid">
	<h1 class="alert alert-dark">{{PAGE_TITLE}}</h1>
    {%for object in object_list %}
			<a class="btn btn-secondary mr-2 mt-2 ml-2 mb-2" role="button" href="{{URL}}{{object.pk}}">{{object}}</a>
    {%endfor%}
</div>

MLOpsTool/templates/includes/navigation.html
{%load static%}
{% block stylesheets %}
	<link href="{% static 'nav_user.css'%}" rel="stylesheet"/>
{% endblock stylesheets %}
<style>
.nav_user p{
    color: white;
    margin-right: 5px;
}
.nav_right{
    margin-right: 0px;
}
.nav_user a{
    padding: 10px 10px 10px 10px;
    margin-right: 5px;

}
</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary nav_user">
<div class="container-fluid">
		{%if user.is_authenticated%}
		<a class="navbar-brand" href="/">MLOpsTool</a>
		{%else%}
		<a class="navbar-brand" href="/">MLOpsTool</a>
		{%endif%}
    
    {%if user.is_authenticated%}
    <div class="collapse navbar-collapse" id="navbarNav"> 
		<ul class="navbar-nav">
			<li class="nav-item ml-1">
              <a role="button" href="{%url 'Data:data_list'%}" class="btn btn-dark">Dataset</a>
			</li>
            <li class="nav-item ml-1">
              <a role="button" href="{%url 'Tag:tag_list' %}" class="btn btn-dark">Tags</a>
			</li>

			<li class="nav-item ml-1">
					<a role="button" href="{%url 'Project:list_project' %}" class="btn btn-dark">Projetos</a>
			</li>
		</ul>
    </div>
    <div class="nav_rigth">
    <p>{{user.username}}</p>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <a class="btn btn-danger" role="button" href="{%url 'User:user_logout'%}">logout</a>
        </li>
    </ul>
    </div>
  </div>
  </div>
    {%else%}
    <div class="nav_rigth">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <a class="btn btn-success" role="button" href="{%url 'User:create_user'%}">sing up</a>
        </li>
    </ul>
    </div>
    </div>
    {%endif%}
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
</nav>