MLOpsTool/MLOpsTool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("User.urls", namespace='User')),
    path('', include("Tag.urls", namespace='Tag')),
    path('', include("Data.urls", namespace='Data')),
    path('', include("Pipeline.urls", namespace='Pipeline')),
    path('', include("Model.urls", namespace='Model')),
    path('', include("PreProcessing.urls", namespace='PreProcessing')),
    path('', include("Project.urls", namespace='Project'))
]

MLOpsTool/Model/urls.py
from django.conf.urls import url
from . import views


app_name = "Model"

urlpatterns = [
    url(
        r"^model/create/(?P<id>\d+)/",
        views.CreateModel.as_view(),
        name="create_model"
    ),
    url(
        r"^model/predict/",
        views.PredictionView.as_view(),
        name="predict_model"
    ),
    url(
        r"model/api/(?P<id>\d+)/report/",
        views.PredictionReport.as_view(),
        name="predict_report"
    )
]

MLOpsTool/Pipeline/urls.py
from django.conf.urls import url
from Pipeline import views


app_name = "Pipeline"

urlpatterns = [
    url(r'pipeline/create/(?P<name>\w+)/', views.add_pipeline,
        name='create_pipeline'),
    url(
        r'pipeline/detail/(?P<pk>\d+)/',
        views.PipelineDetail.as_view(),
        name="detail_pipeline"
       ),
    url(
        r'pipeline/update/data/(?P<pk>\d+)/',
        views.UpdateDataView.as_view(),
        name="update_data"
    ),
    url(
        r'pipeline/start/(?P<id>\d+)/',
        views.start_train,
        name="start_train"
    ),
    url(
        r'pipeline/delete/(?P<id>\d+)/',
        views.delete_pipeline,
        name="delete_pipeline"
    ),
    url(
        r'pipeline/update/threshold/(?P<pk>\w+)/(?P<id>\d+)/',
        views.UpdateThresholdView.as_view(),
        name="update_threshold"
    )
]

MLOpsTool/PreProcessing/urls.py
from django.conf.urls import url
from PreProcessing import views


app_name = "PreProcessing"

urlpatterns = [
    url(
        r'^PreProcessing/create/(?P<id>\d+)/',
        views.CreatePreProcessing.as_view(),
        name="create_preprocessing"
    ),
    url(
        r'^preprocessing/delete/(?P<id>\d+)/',
        views.delete_preprocessing,
        name="delete_preprocessing"
    )
]

MLOpsTool/Tag/urls.py
from django.conf.urls import url
from . import views

app_name = "Tag"

urlpatterns = [
    url(r'tag/list/', views.TagListView.as_view(), name="tag_list"),
    url(r'tag/detail/(?P<pk>\d+)/', views.TagDetailView.as_view(),
        name="tag_detail"),
    url(r'tag/create/', views.TagCreateView.as_view(), name="tag_create"),
]

MLOpsTool/Pipeline/models.py
from django.db import models
from Data.models import Data
from Model.models import Model
from Project.models import Project
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class Pipeline(models.Model):
    class Meta:
        unique_together = (("id", "version"))
    id = models.AutoField(primary_key=True)
    data = models.ForeignKey(
                Data,
                on_delete=models.CASCADE,
                null=True,
                blank=True,
            )
    model = models.ForeignKey(
                Model,
                on_delete=models.CASCADE,
                null=True,
                blank=True,
            )
    project = models.ForeignKey(
                Project,
                on_delete=models.CASCADE,
                null=True,
                blank=True
            )
    version = models.IntegerField()

    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    metric = models.FloatField(default=0.0)
    current_metric = models.FloatField(default=0.0)
    f1_hi = models.FloatField(default=1.0)
    f1_med = models.FloatField(default=0.66)
    f1_low = models.FloatField(default=0.33)
    cut = models.FloatField(default=0.8)

    def __str__(self):
        return "{} | {}".format(self.id, self.version)


@receiver(post_save, sender=Pipeline)
def update_num_models(sender, instance, **kwargs):
    project = Project.objects.get(name=instance.project)
    project.num_models = Pipeline.objects.filter(
        project=instance.project
    ).count()
    project.save()

MLOpsTool/Pipeline/forms.py
from django.forms.models import ModelForm
from Pipeline.models import Pipeline


class ProjectForm(ModelForm):
    class Meta:
        model = Pipeline
        fields = ["version"]

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class UpdateDataForm(ModelForm):
    class Meta:
        model = Pipeline
        fields = ["data"]

    def __init__(self, *args, **kwargs):
        super(UpdateDataForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class UpdateThreshold(ModelForm):
    class Meta:
        model = Pipeline
        fields = ["f1_hi", "f1_med", "f1_low", 'cut']

    def __init__(self, *args, **kwargs):
        super(UpdateThreshold, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

MLOpsTool/Pipeline/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import (
    redirect,
    render
)
from django.views import generic
from Pipeline.models import Pipeline
from Project.models import Project
from .forms import UpdateDataForm, UpdateThreshold
from Pipeline.services import PipelineService
# from Pipeline import forms as pipeline_forms


@login_required
def add_pipeline(request, **kwargs):
    project_name = kwargs.get('name')
    project = Project.objects.get(name=project_name)
    version = project.num_models + 1
    Pipeline.objects.create(
        version=version,
        creator=request.user,
        project=project
    )
    return redirect('Project:detail_project', pk=project_name)


@method_decorator(login_required, name="dispatch")
class PipelineDetail(generic.DetailView):
    model = Pipeline
    template_name = 'Pipeline/Pipeline_detail.html'


@method_decorator(login_required, name="dispatch")
class UpdateDataView(generic.View):
    template_name = "Pipeline/Pipeline_update_data.html"

    def get(self, request, **kwargs):
        form = UpdateDataForm()
        return render(request, self.template_name, {"form": form, **kwargs})

    def post(self, request, **kwargs):
        data_id = request.POST['data']
        pipeline = kwargs.get('pk')
        Pipeline.objects.filter(id=pipeline).update(data_id=data_id)
        return redirect('Pipeline:detail_pipeline', pk=pipeline)


@method_decorator(login_required, name="dispatch")
class UpdateThresholdView(generic.View):
    template_name = "Pipeline/Pipeline_update_threshold.html"

    def get(self, request, **kwargs):
        form = UpdateThreshold()
        return render(request, self.template_name, {"form": form})

    def post(self, request, **kwargs):
        data = {
            "f1_hi": request.POST['f1_hi'],
            "f1_med": request.POST['f1_med'],
            "f1_low": request.POST['f1_low'],
            "cut": request.POST['cut']
        }
        try:
            pipeline = Pipeline.objects.filter(pk=kwargs.get('id'))
            pipeline.update(**data)
            return redirect('Project:detail_project', pk=kwargs.get('pk'))
        except Exception:
            return redirect('Project:detail_project', pk=kwargs.get('pk'))


@login_required
def start_train(request, id):
    pipeline = Pipeline.objects.get(id=id)
    try:
        service = PipelineService(pipeline.id)
        service.run()
        return redirect('Project:detail_project', pk=pipeline.project.pk)
    except Exception as error:
        print(error)
        return redirect('Project:detail_project', pk=pipeline.project.pk)


@login_required
def delete_pipeline(request, id):
    pipeline = Pipeline.objects.get(id=id)
    project = pipeline.project
    if pipeline:
        project.num_models -= 1
        project.save()
        pipeline.delete()
        return redirect('Project:detail_project', pk=pipeline.project.pk)
    return redirect('Project:detail_project', pk=pipeline.project.pk)

MLOpsTool/templates/Pipeline/Pipeline_create.html
{% extends 'layouts/base.html' %}
{% load static%}
{%block title%}Criar Projeto{%endblock title%}
{%block content%}
<style>
.project_form p{
    text-align: inherit;
	color: white;
}
.project_form li{
	list-style: disc outside none;
}
</style>
<div>
	<form method="POST" class="mt-4 text-rigth text-light">
		{%csrf_token%}
		<div class="project_form">
		{{form.as_p}}
		<input class="btn-success" type="submit" value="Criar Pipeline">
		</div>
	</form>
</div>
{%endblock content%}

MLOpsTool/templates/Pipeline/Pipeline_detail.html
{% extends 'layouts/base.html' %}
{% load static%}
{%block title%}Pipeline detail{%endblock title%}
{%block content%}
<div>
		<h1 class="text-white mt-2">Projeto: {{object.project.name}}</h1>
		<h2 class="text-white mt-2"> Versão da pipeline: {{object.version}}</h2>

		<div class="text-white mt-5">
			<div class="mb-5">
				<h3 class="alert alert-info">Dado: </h3>
				{%url 'Pipeline:update_data' pk=object.id as data_url%}
				{%include "includes/add_button_view.html" with urls=data_url%}
				{%if object.data%}
					<a href="#" class="btn btn-block btn-lg btn-warning text-left text-white">Nome: {{object.data.name}} | Versão: {{object.data.version}}</a>
				{%else%}
					<p class="alert alert-warning">Sem dados vinculados</p>
				{%endif%}
			</div>
			<div class="mb-5">
				<h3 class="alert alert-info">Pré processamentos: </h3>
				{%url 'PreProcessing:create_preprocessing' id=object.id as preprocessing%}
    			{%include "includes/add_button_view.html" with urls=preprocessing%}
				{%if object.preprocessing_set.all %}
					{% for pre_processing in object.preprocessing_set.all %}
						<div class="d-flex justify-content-between bg-info p-2 mb-2">
							<div>
								<a href="#" class="btn btn-block btn-lg btn-info text-left text-white">
											Nome: {{pre_processing.name}} | Tipo: {{pre_processing.function.lib}} | Função: {{pre_processing.function.method}} | Coluna Alvo: {{pre_processing.target}}
								</a>
							</div>
							<div>
								<a href="{%url 'PreProcessing:delete_preprocessing' id=pre_processing.id%}"><i class="bi bi-x-circle-fill text-white"></i></a>
							</div>
						</div>
					{%endfor%}
				{%else%}	
					<p class="alert alert-warning">Sem dados vinculados</p>
				{%endif%}
				
			</div>
			<div class="mb-5">
				<h3 class="alert alert-info">Modelo: </h3>
				{%url 'Model:create_model' id=object.id as model_url%}
    			{%include "includes/add_button_view.html" with urls=model_url%}
				{%if object.model%}
				<a href="#" class="btn btn-block btn-lg btn-danger text-left text-white">Nome: {{object.model.name}} | X: {{object.model.x_field}} | Y: {{object.model.y_field}}</a>
				{%else%}
					<p class="alert alert-warning">Sem dados vinculados</p>
				{%endif%}
			</div>
		</div>
		<a href="{%url 'Pipeline:start_train' id=object.id%}" class="btn btn-block btn-lg btn-success"> Treinar Pipeline</a>
</div>
{%endblock content%}

MLOpsTool/templates/Pipeline/Pipeline_update_data.html
{% extends 'layouts/base.html' %}
{% load static%}
{%block title%}Atualizar dados{%endblock title%}
{%block content%}
<style>
.project_form p{
    text-align: inherit;
	color: white;
}
.project_form li{
	list-style: disc outside none;
}
</style>
<div>
	<form method="POST" class="mt-4 text-rigth text-light">
		{%csrf_token%}
		<div class="project_form">
		{{form.as_p}}
		<input class="btn btn-success" type="submit" value="Update data">
		</div>
	</form>
</div>
{%endblock content%}

MLOpsTool/templates/Pipeline/Pipeline_update_threshold.html
{% extends 'layouts/base.html' %}
{% load static%}
{%load custom_tags%}
{%block title%}Update pipeline{%endblock title%}
{%block content%}
<style>
.project_form p{
    text-align: inherit;
	color: white;
}
.project_form li{
	list-style: disc outside none;
}
</style>
<div>
	<form method="POST" class="mt-4 text-rigth text-light">
		{%csrf_token%}
		<div class="project_form">
		{{form.as_p}}
		<button class="btn btn-success" type="submit">
				Update
		</button>
		</div>
	</form>
</div>
{%endblock content%}