MLOpsTool/Data/urls.py
from django.conf.urls import url
from . import views

app_name = "Data"

urlpatterns = [
    url(r'data/list/', views.DataListView.as_view(), name="data_list"),
    url(r'data/detail/(?P<pk>\w+)/', views.DataDetailView.as_view(),
        name="data_detail"),
    url(r'data/create/', views.DataCreateView.as_view(), name="data_create"),
]

MLOpsTool/MLOpsTool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("User.urls", namespace='User')),
    path('', include("Tag.urls", namespace='Tag')),
    path('', include("Data.urls", namespace='Data')),
    path('', include("Pipeline.urls", namespace='Pipeline')),
    path('', include("Model.urls", namespace='Model')),
    path('', include("PreProcessing.urls", namespace='PreProcessing')),
    path('', include("Project.urls", namespace='Project'))
]

MLOpsTool/Tag/urls.py
from django.conf.urls import url
from . import views

app_name = "Tag"

urlpatterns = [
    url(r'tag/list/', views.TagListView.as_view(), name="tag_list"),
    url(r'tag/detail/(?P<pk>\d+)/', views.TagDetailView.as_view(),
        name="tag_detail"),
    url(r'tag/create/', views.TagCreateView.as_view(), name="tag_create"),
]

MLOpsTool/Data/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField


class Data(models.Model):
    class Meta:
        unique_together = (('name', 'version'),)
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    version = models.IntegerField()
    columns = ArrayField(models.CharField(max_length=255, blank=True))
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return "{} | {}".format(self.name, self.version)


class Row(models.Model):
    id = models.AutoField(primary_key=True)
    content = models.JSONField()
    data_ref = models.ForeignKey(
        Data,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return "{} | {}".format(self.id, self.data_ref)

MLOpsTool/Data/forms.py
from django.forms.models import ModelForm
from django import forms
from .models import Data


class DataForm(ModelForm):
    data_file = forms.FileField()

    class Meta:
        model = Data
        fields = "__all__"
        exclude = ["creator", "columns", "content"]

    def __init__(self, *args, **kwargs):
        super(DataForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

MLOpsTool/Data/views.py
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import generic
from .forms import DataForm
from . import models as data
from django.shortcuts import redirect
import pandas as pd


VALID_DATA = {
    "csv": pd.read_csv,
    "json": pd.read_json,
    "parquet": pd.read_parquet,
    "xlsx": pd.read_excel,
}


@method_decorator(login_required, name="dispatch")
class DataCreateView(generic.CreateView):
    model = data.Data
    form_class = DataForm
    template_name = 'Data/Data_create.html'
    success_url = reverse_lazy('Data:data_list')

    def save_rows(self, rows, data_ref):
        list_rows = [
            data.Row(
                content={
                    "data": row
                },
                data_ref=data_ref
            ) for row in rows["data"]
        ]
        data.Row.objects.bulk_create(list_rows)

    def post(self, request):
        type_file = request.FILES["data_file"]._name.split(".")[-1]
        df = VALID_DATA[type_file](request.FILES["data_file"])
        df = df.dropna()
        payload = dict(
            name=request.POST["name"],
            version=request.POST["version"],
            columns=df.columns.to_list(),
            creator=request.user
        )
        data_ref = data.Data.objects.create(**payload)
        rows = df.to_dict('split')
        self.save_rows(rows, data_ref)
        return redirect(self.success_url)


@method_decorator(login_required, name="dispatch")
class DataListView(generic.list.ListView):
    model = data.Data
    template_name = 'Data/Data_list.html'


@method_decorator(login_required, name="dispatch")
class DataDetailView(generic.DetailView):
    model = data.Data
    template_name = "Data/Data_detail.html"

    def get_context_data(self, **kwargs):
        limit = self.request.GET.get('limit', '10')
        context = super(DataDetailView, self).get_context_data(**kwargs)
        data = self.model.objects.get(id=context["object"].id)
        context["row_set"] = data.row_set.all()[:int(limit)]
        return context

MLOpsTool/templates/Data/Data_create.html
{% extends 'layouts/base.html' %}
{% load static%}
{%block title%}Criar Dataset{%endblock title%}
{%block content%}
<style>
.project_form p{
    text-align: inherit;
	color: white;
}
.project_form li{
	list-style: disc outside none;
}
.not-visible {
  display: none;
}
</style>
<form method="POST" action="POST" class="mt-4 text-rigth text-light" enctype="multipart/form-data" id="form-data">
    {%csrf_token%}
    <div class="project_form">
    {{form.as_p}}
    <div id="progress-box" class="not-visible"><p>Progress</p></div>
    <div id="cancel-box" class="not-visible">
      <button id="cancel-button" class="btn btn-danger mb-3">cancel</button>
    </div>

    <input class="btn-success" type="submit" value="Criar Dataset">
    </div>
    </form>
{%endblock content%}

MLOpsTool/templates/Data/Data_detail.html
{% extends 'layouts/base.html' %}
{% load static%}
{%block title%}Dataset {{object.name}} {{object.version}}{%endblock title%}
{%block content%}
<div class="conteiner-fluid text-white">
  <table class="table justify-content-center text-white">
  <thead>
  {% for column in object.columns%}
      <th>{{column}}</th>
  {%endfor%}
  </thead>
  <tbody>
    {%for rows in row_set%}
        <tr scope="row">
          {%for key, content in rows.content.items%}
            {%for value in content%}
              <td style="word-break:break-all; overflow:hidden" >{{value}}</td>
            {%endfor%}
          {%endfor%}
        </tr>
      {%endfor%}
  </tbody>
  </table>
</div>

{%endblock content%}

MLOpsTool/templates/Data/Data_list.html
{% extends 'layouts/base.html' %}
{% load static%}
{%block title%}Datasets{%endblock title%}
{%block content%}
<div class="conteiner-fluid">
    {% url 'Data:data_create' as data_url %}
    {% include "includes/add_button_view.html" with urls=data_url%}
    {% include "includes/list_object_view.html" with PAGE_TITLE="Lista de Datasets" URL="/data/detail/"%}
</div>
{%endblock content%}