MLOpsTool/MLOpsTool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("User.urls", namespace='User')),
    path('', include("Tag.urls", namespace='Tag')),
    path('', include("Data.urls", namespace='Data')),
    path('', include("Pipeline.urls", namespace='Pipeline')),
    path('', include("Model.urls", namespace='Model')),
    path('', include("PreProcessing.urls", namespace='PreProcessing')),
    path('', include("Project.urls", namespace='Project'))
]

MLOpsTool/Pipeline/urls.py
from django.conf.urls import url
from Pipeline import views


app_name = "Pipeline"

urlpatterns = [
    url(r'pipeline/create/(?P<name>\w+)/', views.add_pipeline,
        name='create_pipeline'),
    url(
        r'pipeline/detail/(?P<pk>\d+)/',
        views.PipelineDetail.as_view(),
        name="detail_pipeline"
       ),
    url(
        r'pipeline/update/data/(?P<pk>\d+)/',
        views.UpdateDataView.as_view(),
        name="update_data"
    ),
    url(
        r'pipeline/start/(?P<id>\d+)/',
        views.start_train,
        name="start_train"
    ),
    url(
        r'pipeline/delete/(?P<id>\d+)/',
        views.delete_pipeline,
        name="delete_pipeline"
    ),
    url(
        r'pipeline/update/threshold/(?P<pk>\w+)/(?P<id>\d+)/',
        views.UpdateThresholdView.as_view(),
        name="update_threshold"
    )
]

MLOpsTool/Project/urls.py
from django.conf.urls import url
from Project import views


app_name = "Project"

urlpatterns = [
    url(r'project/list/', views.ProjectListView.as_view(),
        name='list_project'),
    url(r'project/create/', views.ProjectCreateView.as_view(),
        name='create_project'),
    url(r'project/detail/(?P<pk>\w+)/', views.ProjectDetailView.as_view(),
        name='detail_project'),

]

MLOpsTool/Tag/urls.py
from django.conf.urls import url
from . import views

app_name = "Tag"

urlpatterns = [
    url(r'tag/list/', views.TagListView.as_view(), name="tag_list"),
    url(r'tag/detail/(?P<pk>\d+)/', views.TagDetailView.as_view(),
        name="tag_detail"),
    url(r'tag/create/', views.TagCreateView.as_view(), name="tag_create"),
]

MLOpsTool/Pipeline/models.py
from django.db import models
from Data.models import Data
from Model.models import Model
from Project.models import Project
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class Pipeline(models.Model):
    class Meta:
        unique_together = (("id", "version"))
    id = models.AutoField(primary_key=True)
    data = models.ForeignKey(
                Data,
                on_delete=models.CASCADE,
                null=True,
                blank=True,
            )
    model = models.ForeignKey(
                Model,
                on_delete=models.CASCADE,
                null=True,
                blank=True,
            )
    project = models.ForeignKey(
                Project,
                on_delete=models.CASCADE,
                null=True,
                blank=True
            )
    version = models.IntegerField()

    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    metric = models.FloatField(default=0.0)
    current_metric = models.FloatField(default=0.0)
    f1_hi = models.FloatField(default=1.0)
    f1_med = models.FloatField(default=0.66)
    f1_low = models.FloatField(default=0.33)
    cut = models.FloatField(default=0.8)

    def __str__(self):
        return "{} | {}".format(self.id, self.version)


@receiver(post_save, sender=Pipeline)
def update_num_models(sender, instance, **kwargs):
    project = Project.objects.get(name=instance.project)
    project.num_models = Pipeline.objects.filter(
        project=instance.project
    ).count()
    project.save()

MLOpsTool/Project/models.py
from django.db import models
from Tag.models import Tag
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=255, primary_key=True)
    project_tag = models.ManyToManyField(
                Tag,
                blank=True
            )
    description = models.TextField(null=True)
    creation_date = models.DateTimeField(auto_now=True)
    update_field = models.DateTimeField(auto_now=True)
    num_models = models.IntegerField(default=0)
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    token = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return "{}".format(self.name)

MLOpsTool/Project/forms.py
from django.forms.models import ModelForm
from django.forms.widgets import CheckboxSelectMultiple
from Project.models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = "__all__"
        exclude = ["num_models", "creator", "token"]
        widgets = {
            "project_tag": CheckboxSelectMultiple,
        }

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.field.label == "Project tag":
                continue
            visible.field.widget.attrs['class'] = 'form-control'

MLOpsTool/Project/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import (
    redirect,
)
from django.views import generic
from Project import models as project
from Project import forms as project_forms
from uuid import uuid4


@method_decorator(login_required, name='dispatch')
class ProjectListView(generic.list.ListView):
    model = project.Project
    template_name = 'Project/Project_list.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        context["PAGE_TITLE"] = "LISTA DE PROJETOS"
        context["URL"] = "/project/detail/"
        return context


@method_decorator(login_required, name='dispatch')
class ProjectCreateView(generic.CreateView):
    model = project.Project
    form_class = project_forms.ProjectForm
    template_name = 'Project/Project_create.html'
    success_url = reverse_lazy('Project:list_project')

    def post(self, request):
        token = uuid4().hex
        data = dict(
            name=request.POST["name"].replace(' ', '_'),
            description=request.POST["description"],
            creator=request.user,
            token=token
        )
        obj = project.Project.objects.create(**data)
        try:
            obj.project_tag.set(request.POST["project_tag"])
            obj.save()
        except Exception:
            obj.save()
        return redirect(reverse_lazy("Project:list_project"))


@method_decorator(login_required, name='dispatch')
class ProjectDetailView(generic.DetailView):
    model = project.Project
    template_name = "Project/Project_detail.html"

MLOpsTool/templates/Project/Project_create.html
{% extends 'layouts/base.html' %}
{% load static%}
{%block title%}Criar Projeto{%endblock title%}
{%block content%}
<style>
.project_form p{
    text-align: inherit;
	color: white;
}
.project_form li{
	list-style: disc outside none;
}
</style>
<form method="POST" class="mt-4 text-rigth text-light">
    {%csrf_token%}
    <div class="project_form">
    {{form.as_p}}
    <input class="btn btn-success" type="submit" value="Criar Projeto">
    </div>
</form>
{%endblock content%}

MLOpsTool/templates/Project/Project_detail.html
{% extends 'layouts/base.html' %}
{% load static%}
{%block title%}Projeto {{object.name}}{%endblock title%}
{%block content%}
<div class="conteiner-fluid text-light">
		<div>
				<h1 class="text-white mt-1">Token do projeto: {{object.token}}</h1>
				<div>
					<h3>Tags: </h3>
					{%for tag in object.project_tag.all%}
						<a class="btn btn-success mr-2 mt-2 ml-2 mb-2" role="button" href="#">{{tag}}</a>
					{%endfor%}
				</div>
				<table class="table justify-content-center bg-info">
					<thead class="bg-primary">
						<th>Nome</th>
						<th>Descrição</th>
						<th>Número de Modelos</th>
						<th>Autor</th>
					</thead>
					<tbody>
						<tr scope="row">
								<td>{{object.name}}</td>
								<td>{{object.description}}</td>
								<td>{{object.num_models}}</td>
								<td>{{object.creator}}</td>
						</tr>
					</tbody>
				</table>
		</div>
		<div>
			<h1 class="alert alert-info mt-2">Pipelines</h1>
			{%url 'Pipeline:create_pipeline' name=object.name as pipeline_url%}
			{%include "includes/add_button_view.html" with urls=pipeline_url%}
			{%if not object.pipeline_set.all %}
				<h2 class="alert alert-warning">Sem pipelines disponíveis</h2>
			{%endif%}
			{%for pipeline in object.pipeline_set.all%}
			<div class="d-flex justify-content-between bg-info p-3 mb-2">
					<div>
					<a href="{%url 'Pipeline:detail_pipeline' pk=pipeline.id%}" class="btn btn-block btn-lg btn-info text-left">
							<div>Pipeline version: {{pipeline.version}} identificador: {{pipeline.id}}</div>

					</a>
					</div>
					<div>
								<div>
								 {%if pipeline.current_metric <= pipeline.f1_low%}
									Atual F1: <b class="bg-danger p-2 mr-2">{{pipeline.current_metric|floatformat:"2"}}</b>
								 {%elif pipeline.current_metric <= pipeline.f1_med%}
									Atual F1: <b class="bg-warning p-2 mr-2">{{pipeline.current_metric|floatformat:"2"}}</b>
								 {%else%}
									Atual F1: <b class="bg-success p-2 mr-2">{{pipeline.current_metric|floatformat:"2"}}</b>
								 {%endif%}
								 {%if pipeline.metric <= pipeline.f1_low%}
								 	Métrica F1: <b class="bg-danger p-2 mr-2">{{pipeline.metric}}</b>
								 {%elif pipeline.metric <= pipeline.f1_med%}
								 	Métrica F1: <b class="bg-warning p-2 mr-2">{{pipeline.metric}}</b>
								 {%else%}
								 	Métrica F1: <b class="bg-success p-2 mr-2">{{pipeline.metric}}</b>
								{%endif%}
								<a href="{%url 'Pipeline:update_threshold' pk=object.pk id=pipeline.id%}"><i class="bi bi-pencil-square mr-2 text-white"></i></a><a href="{%url 'Pipeline:delete_pipeline' id=pipeline.id%}"><i class="bi bi-x-circle-fill text-white"></i></a></div>
							</div>
				</div>
			{% endfor %}
		</div>
</div>
{%endblock content%}

MLOpsTool/templates/Project/Project_list.html
{% extends 'layouts/base.html' %}
{% load static%}
{%block title%}Projetos{%endblock title%}
{%block content%}
<div class="conteiner-fluid">
    {%url 'Project:create_project' as url_create%}
    {%include "includes/add_button_view.html" with urls=url_create%}
	{%include "includes/list_object_view.html"%}
</div>
{%endblock content%}